# Generated by Django 4.2.5 on 2024-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weather_condition',
            field=models.CharField(choices=[('Rainy', 'Rainy'), ('Hot', 'Hot'), ('Snowy', 'Snowy'), ('Humid', 'Humid'), ('Normal', 'Normal')], default='Normal', help_text='Weather condition suitable for this product', max_length=50),
        ),
    ]
