# Generated by Django 4.2.5 on 2024-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_weathercondition_remove_product_weather_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weather_conditions',
        ),
        migrations.AddField(
            model_name='product',
            name='weather_condition',
            field=models.CharField(choices=[('Rainy', 'Rainy'), ('Hot', 'Hot'), ('Snowy', 'Snowy'), ('Humid', 'Humid'), ('Normal', 'Normal')], default='Normal', help_text='Weather condition suitable for this product', max_length=50),
        ),
        migrations.DeleteModel(
            name='WeatherCondition',
        ),
    ]
